# Copyright (c) 2023 Uber Technologies, Inc.
#
# <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# <p>http://www.apache.org/licenses/LICENSE-2.0
#
# <p>Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing permissions and
# limitations under the License.

# adapted from https://github.com/uber/piranha/blob/master/src/cleanup_rules/go/rules.toml#L338-L372



# Before :
#  {
#     someStepsBefore();
#     {
#        someSteps();
#     }
#     someStepsAfter();
#  }
# After :
#  {
#     someStepsBefore();
#        someSteps();
#     someStepsAfter();
#  }
#
# Note that we need to tag basically all nodes here.
# Including not so obvious ones: @outer.stmt_list and @outer.block
[[rules]]
name = "remove_unnecessary_nested_block"
query = """
(
    (block
        (statement_list
            (_)* @pre
            ((block
                (statement_list) @nested.statements
            ) @nested.block)
            (_)* @post
        ) @outer.stmt_list
    ) @outer.block
)
"""
replace = "@nested.statements"
replace_node = "nested.block"
is_seed_rule = false
