version: '3.9'
services:
  database:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'codemod'
    ports:
      - '5432:5432'
    networks:
      - codemod-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - codemod-network

networks:
  codemod-network:
    driver: bridge
