packages:
    - apps/**
    - packages/**
    - "!**/.next/**"
catalog:
    "@aws-sdk/client-s3": ^3.549.0
    "@aws-sdk/s3-request-presigner": ^3.549.0
    "@babel/plugin-syntax-flow": ^7.14.5
    "@babel/plugin-transform-react-jsx": ^7.14.9
    "@babel/preset-typescript": ^7.24.1
    "@babel/traverse": 7.24.1
    "@babel/types": 7.21.2
    "@clerk/backend": 0.36.0
    "@clerk/clerk-react": 4.30.3
    "@clerk/fastify": 0.6.27
    "@clerk/nextjs": 4.29.3
    "@clerk/themes": 1.7.10
    "@faker-js/faker": ^8.4.1
    "@fastify/busboy": ^2.1.1
    "@fastify/cors": 8.5.0
    "@fastify/multipart": ^8.1.0
    "@fastify/rate-limit": 9.0.1
    "@hookform/resolvers": ^3.3.2
    "@phosphor-icons/react": ^2.0.10
    "@preact/preset-vite": ^2.5.0
    "@prisma/client": 5.10.2
    "@radix-ui/react-alert-dialog": ^1.0.4
    "@radix-ui/react-avatar": ^1.0.4
    "@radix-ui/react-dialog": ^1.0.4
    "@radix-ui/react-dropdown-menu": ^2.0.5
    "@radix-ui/react-label": ^2.0.2
    "@radix-ui/react-select": ^1.2.2
    "@radix-ui/react-separator": ^1.0.3
    "@radix-ui/react-slot": ^1.0.2
    "@radix-ui/react-switch": ^1.0.3
    "@radix-ui/react-tabs": ^1.0.4
    "@radix-ui/react-toast": ^1.1.5
    "@radix-ui/react-tooltip": ^1.0.6
    "@reduxjs/toolkit": ^1.9.5
    "@svgr/hast-util-to-babel-ast": ^7.0.0
    "@swc/wasm-web": ^1.3.100
    "@t3-oss/env-nextjs": ^0.7.1
    "@testing-library/dom": ^9.0.0
    "@testing-library/jest-dom": ^5.16.5
    "@testing-library/react": ^13.4.0
    "@testing-library/user-event": ^13.5.0
    "@tippyjs/react": ^4.2.6
    "@tiptap/extension-code-block-lowlight": ^2.1.8
    "@tiptap/pm": ^2.1.8
    "@tiptap/react": ^2.1.8
    "@tiptap/starter-kit": ^2.1.8
    "@types/babel__traverse": ^7.20.1
    "@types/chai": ^4.3.4
    "@types/columnify": ^1.5.4
    "@types/diff": ^5.0.3
    "@types/glob": ^8.0.0
    "@types/inquirer": ^9.0.7
    "@types/jest": ^27.5.2
    "@types/js-beautify": ^1.14.3
    "@types/js-yaml": 4.0.9
    "@types/mocha": ^10.0.1
    "@types/ms": ^0.7.34
    "@types/pako": ^2.0.0
    "@types/parse-github-url": 1.0.3
    "@types/pg": ^8.11.2
    "@types/prettier": ^2.7.3
    "@types/react-dom": ^18.0.11
    "@types/react-syntax-highlighter": ^15.5.6
    "@types/react-treeview": ^0.4.3
    "@types/react-virtualized": ^9.21.21
    "@types/react-virtualized-auto-sizer": ^1.0.1
    "@types/sinon": ^10.0.20
    "@types/supertest": ^6.0.2
    "@types/tar-stream": ^3.1.3
    "@types/testing-library__jest-dom": ^5.14.5
    "@types/vscode": ^1.74.0
    "@types/vscode-webview": ^1.57.1
    "@types/yargs": ^17.0.13
    "@vercel/analytics": ^1.0.2
    "@vitejs/plugin-react": ^4.0.0
    "@vitest/coverage-v8": ^1.0.1
    "@vscode/extension-telemetry": ^0.7.7
    "@vscode/test-electron": ^2.2.2
    "@vscode/vsce": ^2.22.0
    "@vscode/webview-ui-toolkit": ^1.2.2
    "@vue/compiler-sfc": ^3.4.21
    applicationinsights: ^2.9.1
    assert: ^2.0.0
    ast-node-builder: ^4.2.1
    ast-types: ^0.14.2
    autoprefixer: ^10.4.14
    axios: ^1.6.8
    axios-retry: ^4.0.0
    bl: ^6.0.11
    chai: ^4.3.7
    change-case: ^5.2.0
    chatgpt: 5.2.5
    chromadb: 1.7.2
    class-variance-authority: ^0.7.0
    classnames: ^2.3.2
    clsx: ^2.0.0
    columnify: ^1.6.0
    concurrently: ^8.2.0
    constants-browserify: ^1.0.0
    cosmiconfig: ^8.3.6
    cron: ^3.1.6
    cspell-cli: ^6.17.1
    csstype: ^3.1.1
    diff: ^5.1.0
    dotenv: ^16.4.5
    dotenv-cli: ^7.4.1
    exponential-backoff: ^3.1.1
    fast-deep-equal: ^3.1.3
    fastify: 4.25.1
    fastify-plugin: 4.5.1
    form-data: ^4.0.0
    fuse.js: ^7.0.0
    fuzzysort: ^2.0.4
    husky: ^8.0.3
    inquirer: ^9.2.16
    io-ts: ^2.2.20
    io-ts-reporters: ^2.0.1
    io-ts-types: ^0.5.19
    js-beautify: ^1.14.11
    js-yaml: 4.1.0
    json-schema-to-typescript: ^13.1.2
    jszip: ^3.10.1
    katex: ^0.16.10
    keytar: ^7.9.0
    langchain: 0.0.209
    lint-staged: ^15.1.0
    lowlight: ^3.0.0
    lru-cache: 10.1.0
    lucide-react: ^0.265.0
    mdast-util-from-markdown: ^2.0.0
    mdast-util-mdx: ^3.0.0
    mdast-util-to-markdown: ^2.1.0
    micromark-extension-mdxjs: ^2.0.0
    minimatch: ^9.0.3
    monaco-editor-webpack-plugin: ^7.0.1
    monocle-ts: ^2.3.13
    ms: ^2.1.3
    newtype-ts: ^0.3.5
    next: 14.0.3
    nock: ^13.5.1
    nodemon: 3.0.2
    openai: 4.23.0
    openai-edge: 1.2.2
    ora: ^8.0.1
    os-browserify: ^0.3.0
    pako: ^2.1.0
    parse-github-url: 1.0.2
    pg: ^8.11.3
    postcss: ^8.4.21
    preact: ^10.13.2
    preact-compat: ^3.19.0
    prisma: ^5.10.2
    prisma-json-types-generator: ^3.0.4
    raw-loader: ^4.0.2
    rc-progress: ^3.4.1
    react: ^18.2.0
    react-dom: ^18.2.0
    react-hook-form: ^7.48.2
    react-hot-toast: ^2.4.0
    react-markdown: ^8.0.7
    react-syntax-highlighter: ^15.5.0
    react-textarea-autosize: ^8.5.2
    react-toastify: ^9.1.3
    react-tooltip: ^5.9.0
    react-treeview: ^0.4.7
    reactjs-popup: ^2.0.5
    recast: ^0.22.0
    redux-persist: ^6.0.0
    rehype-parse: ^8.0.4
    remark-gfm: ^3.0.1
    remark-math: ^5.1.1
    replicate: 0.25.2
    sequelize: ^6.37.1
    sqlite3: ^5.1.7
    supertest: ^6.3.4
    tailwind-merge: ^1.10.0
    tailwindcss: ^3.3.3
    tailwindcss-animate: ^1.0.7
    tar-stream: ^3.1.7
    terminal-link: ^3.0.0
    tippy.js: ^6.3.7
    ts-loader: ^9.4.2
    tslib: 2.4.1
    turbo: ^1.10.14
    umd-compat-loader: ^2.1.2
    unified: ^10.1.2
    unist-util-filter: ^5.0.1
    unist-util-visit: ^5.0.0
    universal-base64url: ^1.1.0
    valibot: ^0.24.1
    vite: ^4.5.3
    vite-plugin-monaco-editor: ^1.1.0
    vite-plugin-svgr: ^2.4.0
    vite-tsconfig-paths: ^4.2.0
    vue-sfc-descriptor-to-string: ^2.0.0
    web-vitals: ^2.1.4
    webpack: 5.91.0
    webpack-cli: 5.1.4
    yargs: ^17.6.2
    zod: 3.22.3
    zod-prisma-types: ^3.1.6
    zustand: ^4.5.2
