packages:
  - apps/**
  - packages/**
  - "!**/.next/**"

catalog:
  "@babel/core": ^7.24.7
  "@ast-grep/cli": ^0.32.0
  "@ast-grep/napi": ^0.32.0
  "@biomejs/biome": ^1.6.4
  "@clerk/backend": 1.23.5
  "@faker-js/faker": ^8.4.1
  "@fastify/cors": 8.5.0
  "@fastify/multipart": ^8.1.0
  "@fastify/rate-limit": 9.0.1
  "@octokit/rest": ^20.0.2
  "@radix-ui/react-alert-dialog": ^1.0.4
  "@radix-ui/react-avatar": ^1.0.4
  "@radix-ui/react-dialog": ^1.0.4
  "@radix-ui/react-dropdown-menu": ^2.0.5
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-progress": ^1.0.3
  "@radix-ui/react-select": ^1.2.2
  "@radix-ui/react-separator": ^1.0.3
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-switch": ^1.0.3
  "@radix-ui/react-tabs": ^1.0.4
  "@radix-ui/react-toast": ^1.1.5
  "@radix-ui/react-tooltip": ^1.0.6
  "@types/diff": ^5.0.3
  "@types/glob": ^8.0.0
  "@types/inquirer": ^9.0.7
  "@types/node": ^22 # use lasted 22 version
  "@types/pako": ^2.0.0

  "@types/react-dom": ^18.0.11
  "@types/react-syntax-highlighter": ^15.5.6
  "@types/react-treeview": ^0.4.3
  "@types/react-virtualized": ^9.21.21
  "@types/react-virtualized-auto-sizer": ^1.0.1
  "@types/tar": ^6.1.11
  "@types/tar-stream": ^3.1.3
  "@types/vscode": ^1.74.0
  "@types/vscode-webview": ^1.57.1
  "@types/ws": ^8.5.11
  "@unkey/api": ^0.26.2
  ast-node-builder: ^4.2.1
  ast-types: ^0.14.2
  axios: ^1.8.2
  axios-retry: ^4.0.0
  bullmq: ^5.7.5
  change-case: ^5.2.0
  class-variance-authority: ^0.7.0
  clsx: ^2.0.0
  cobe: ^0.6.3
  colors-cli: ^1.0.33
  csstype: ^3.1.1
  cva: npm:class-variance-authority@^0.7.0
  diff: ^5.1.0
  dotenv: ^16.4.5
  fastify: 4.28.1
  glob: ^10.4.5
  husky: ^8.0.3
  inquirer: ^9.2.16
  katex: ^0.16.21
  keytar: ^7.9.0
  ms: ^2.1.3
  next: ^14.2.3
  pako: ^2.1.0
  pg: ^8.11.3
  prop-types: ^15.8.1
  react-chartjs-2: ^5.2.0
  react-hook-form: ^7.48.2
  react-hot-toast: ^2.4.0
  react-markdown: ^8.0.7
  react-syntax-highlighter: ^15.5.0
  react-textarea-autosize: ^8.5.2
  react-toastify: ^9.1.3
  react-tooltip: ^5.9.0
  react-treeview: ^0.4.7
  react-use: 17.5.1
  react: ^18.3.1
  react-dom: ^18.3.1
  reactjs-popup: ^2.0.5
  replicate: 0.25.2
  simple-git: ^3.24.0
  tar: ^6.1.15
  tar-stream: ^3.1.7
  typescript: ^5.8.3
  underscore: ^1.13.1
  unified: ^10.1.2
  valibot: ^1.1.0
  wrap-ansi: ^9.0.0
  ws: ^8.18.0
  zod: 4.0.5
