/*! @license
The MIT License (MIT)

Copyright (c) 2024 yugal41735

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

*/
"use strict";Object.defineProperty(exports,"__esModule",{value:true});Object.defineProperty(exports,"default",{enumerable:true,get:function(){return transform}});function transform(file,api,options){const j=api.jscodeshift;const root=j(file.source);let dirtyFlag=false;root.find(j.VariableDeclarator,{id:{type:"Identifier"},init:{type:"CallExpression",callee:{type:"Identifier",name:"useSubscribe"}}}).forEach(path=>{const expressionStatement=j.expressionStatement(path.node.init);j(path.parent).replaceWith(expressionStatement);dirtyFlag=true});root.find(j.CallExpression,{callee:{type:"Identifier",name:"useTracker"}}).forEach(path=>{const callback=path.node.arguments[0];if(j.FunctionExpression.check(callback)||j.ArrowFunctionExpression.check(callback)){const body=callback.body;if(j.BlockStatement.check(body)){const returnStatement=body.body.find(stmt=>j.ReturnStatement.check(stmt));if(returnStatement){const returnValue=returnStatement.argument;if(j.CallExpression.check(returnValue)){const callee=returnValue.callee;if(j.MemberExpression.check(callee)&&j.Identifier.check(callee.object)&&callee.object.name==="Meteor"&&j.Identifier.check(callee.property)){if(callee.property.name==="user"){callee.property.name="userAsync";path.node.arguments.unshift(j.literal("user"));dirtyFlag=true}}else if(j.CallExpression.check(returnValue)&&j.MemberExpression.check(returnValue.callee)&&j.Identifier.check(returnValue.callee.property)&&returnValue.callee.property.name==="fetch"){returnValue.callee.property.name="fetchAsync";path.node.arguments.unshift(j.literal("tasksByUser"));dirtyFlag=true}}}}else if(j.CallExpression.check(body)){const callee=body.callee;if(j.MemberExpression.check(callee)&&j.Identifier.check(callee.object)&&callee.object.name==="Meteor"&&j.Identifier.check(callee.property)){if(callee.property.name==="user"){callee.property.name="userAsync";path.node.arguments.unshift(j.literal("user"));dirtyFlag=true}}else if(j.CallExpression.check(body)&&j.MemberExpression.check(body.callee)&&j.Identifier.check(body.callee.property)&&body.callee.property.name==="fetch"){body.callee.property.name="fetchAsync";path.node.arguments.unshift(j.literal("tasksByUser"));dirtyFlag=true}}}});root.find(j.IfStatement,{test:{type:"CallExpression",callee:{type:"Identifier",name:"isLoading"}}}).forEach(path=>{j(path).remove();dirtyFlag=true});root.find(j.ImportDeclaration,{source:{value:"meteor/react-meteor-data"}}).forEach(path=>{path.node.source.value="meteor/react-meteor-data/suspense";dirtyFlag=true});return dirtyFlag?root.toSource():undefined}