version: '3.9'
services:
    studio-database:
        image: 'postgres:16'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'studio'
        ports:
            - '5432:5432'
        networks:
            - 'codemod-local-network'
    backend:
        build:
            context: ../..
            dockerfile: apps/backend/development.Dockerfile
        environment:
            PORT: '8081'
            CLERK_DISABLED: 'true'
            DATABASE_URI: 'postgres://postgres:postgres@studio-database:5432/studio'
        ports:
            - '8081:8081'
        networks:
            - 'codemod-local-network'
        volumes:
            - ./src:/app/backend/src

networks:
    codemod-local-network:
