version: '3.9'
services:
  backend:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    environment:
      PORT: ${PORT}
      PEPPER: ${PEPPER}
      SIGNATURE_PRIVATE_KEY: ${SIGNATURE_PRIVATE_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_JWT_KEY: ${CLERK_JWT_KEY}
      CLERK_PUBLISH_KEY: ${CLERK_PUBLISH_KEY}
      DATABASE_URI: ${DATABASE_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TASK_MANAGER_QUEUE_NAME: ${TASK_MANAGER_QUEUE_NAME}
      CODEMOD_COM_API_URL: ${CODEMOD_COM_API_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '8081:8081'
    networks:
      - codemod-network

networks:
  codemod-network:
    driver: bridge
