version: '3.9'
services:
  codemod-backend:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    environment:
      PORT: 8081
      DATABASE_URI: postgresql://postgres:postgres@database:5432/codemod?schema=public
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      X_CODEMOD_ACCESS_TOKEN: ${X_CODEMOD_ACCESS_TOKEN}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_JWT_KEY: ${CLERK_JWT_KEY}
      CLERK_PUBLISH_KEY: ${CLERK_PUBLISH_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TASK_MANAGER_QUEUE_NAME: ${TASK_MANAGER_QUEUE_NAME}
      PEPPER: ${PEPPER}
      SIGNATURE_PRIVATE_KEY: ${SIGNATURE_PRIVATE_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    ports:
      - '8081:8081'
    networks:
      - codemod-network

networks:
  codemod-network:
    driver: bridge
