[package]
name = "butterflow-scheduler"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
butterflow-models = { path = "../models" }
tokio = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }

[dev-dependencies]
async-trait = "0.1"
chrono = "0.4"

[features]
default = []
