version: '3.9'
services:
  modgpt-backend:
    build:
      context: ../..
      dockerfile: apps/modgpt/Dockerfile
    environment:
      PORT: ${PORT}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      REPLICATE_API_KEY: ${REPLICATE_API_KEY}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '8082:8082'
    networks:
      - codemod-network

networks:
  codemod-network:
    driver: bridge
