version: '3.9'
services:
  modgpt-backend:
    build:
      context: ../..
      dockerfile: apps/modgpt/Dockerfile
    environment:
      PORT: ${PORT}
      X_CODEMOD_ACCESS_TOKEN: ${X_CODEMOD_ACCESS_TOKEN}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_JWT_KEY: ${CLERK_JWT_KEY}
      CLERK_PUBLISH_KEY: ${CLERK_PUBLISH_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      REPLICATE_API_KEY: ${REPLICATE_API_KEY}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
    ports:
      - '8082:8082'
    networks:
      - codemod-network

networks:
  codemod-network:
    driver: bridge
