WebAppInternals.reloadClientPrograms();
WebAppInternals.pauseClient();
WebAppInternals.generateClientProgram();
WebAppInternals.generateBoilerplate();
WebAppInternals.setInlineScriptsAllowed();
WebAppInternals.enableSubresourceIntegrity();
WebAppInternals.setBundledJsCssUrlRewriteHook();
WebAppInternals.setBundledJsCssPrefix();
WebAppInternals.getBoilerplate;