id: console-log
language: javascript
rule:
  pattern: console.log($$$ARGS)
fix: logger.info($$$ARGS)
message: "Found console.log statement"
---
id: var-declaration
language: javascript
rule:
  pattern: var $VAR = $VALUE
fix: let $VAR = $VALUE
message: "Found var declaration (prefer let/const)"
---
id: function-declaration
language: typescript
rule:
  pattern: function $NAME($$$) { $$$ }
fix: function $NAME($$$) { $$$ }
message: "Found function declaration"
---
id: interface-declaration
language: typescript
rule:
  pattern: interface $NAME { $$$ }
message: "Found interface declaration"
