version: "1"
nodes:
  - id: apply-rules
    name: Apply AST-grep Rules
    steps:
      - name: "Scan TypeScript files only"
        ast-grep:
          include:
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/*.test.ts"
            - "**/*.spec.ts"
          base_path: "src"
          config_file: "rules/config.yml"
