export const BAD_REQUEST = "BAD_REQUEST";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

export const CODEMOD_NOT_FOUND = "CODEMOD_NOT_FOUND";

export const CODEMOD_VERSION_EXISTS = "CODEMOD_VERSION_EXISTS";
export const NO_MAIN_FILE_FOUND = "NO_MAIN_FILE_FOUND";
export const NO_CONFIG_FILE_FOUND = "NO_CONFIG_FILE_FOUND";
export const NO_CODEMOD_TO_PUBLISH = "NO_CODEMOD_TO_PUBLISH";
export const CODEMOD_CONFIG_INVALID = "CODEMOD_CONFIG_INVALID";
export const CODEMOD_NAME_TAKEN = "CODEMOD_NAME_TAKEN";
