# Codemod Studio uses ast-grep to match and rewrite code.
# https://ast-grep.github.io/guide/rule-config.html#rule
id: replace-io-with-logger
language: elixir
rule:
  any:
    - pattern: IO.puts($ARG)
    - pattern: IO.inspect($$$ARGS)
fix: |
  Logger.info($ARG)$ARGS