# Convert deprecated MySQL functions to modern PDO equivalents
# This helps modernize legacy PHP codebases
id: mysql-to-pdo-conversion
language: php
rule:
  any:
    - kind: function_call_expression
      all:
        - has:
            field: function
            kind: name
            regex: ^mysql_query$
    - kind: function_call_expression
      all:
        - has:
            field: function
            kind: name
            regex: ^mysql_fetch_array$
    - kind: function_call_expression
      all:
        - has:
            field: function
            kind: name
            regex: ^mysql_fetch_assoc$
    - kind: function_call_expression
      all:
        - has:
            field: function
            kind: name
            regex: ^mysql_connect$
    - kind: function_call_expression
      all:
        - has:
            field: function
            kind: name
            regex: ^mysql_close$
fix: |
  # Note: ast-grep fix doesn't support conditional logic
  # Use the napi script for proper transformation logic
  $pdo->modernMethod()