rules:
  - id: var-to-const
    message: Convert var to const
    language: javascript
    rule:
      pattern: var $NAME = $VALUE
    fix: const $NAME = $VALUE

  - id: remove-console-log
    message: Remove console.log statements
    language: javascript
    rule:
      pattern: console.log($$$ARGS)
    fix: ""
