# Codemod Studio uses ast-grep to match and rewrite code.
# https://ast-grep.github.io/guide/rule-config.html#rule
id: replace-println-with-logging
language: rust
rule:
  pattern: println!($$$ARGS)
fix:
  log::info!($$$ARGS)