[package]
name = "codemod-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
rquickjs = { version = "0.9.0", default-features = false, features = [
  "loader",
  "futures",
  "macro",
] }

tree-sitter-facade-sg = "0.25.3"

web-tree-sitter-sg = { git = "https://github.com/mohebifar/tree-sitter-wasm.git", branch = "upgrade/0.25.4" }

thiserror = "1.0.65"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.130"

wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Native dependencies only - use native ast-grep
ast-grep-core = { version = "=0.38.1" }
ast-grep-config = { version = "=0.38.1" }
ast-grep-language = { version = "=0.38.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# WASM dependencies - for browser environments
ast-grep-core = { version = "=0.38.1" }
ast-grep-config = { version = "=0.38.1" }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-tree-sitter-sg = { git = "https://github.com/mohebifar/tree-sitter-wasm.git", branch = "upgrade/0.25.4", optional = true }

[features]
default = []
wasm = ["web-tree-sitter-sg", "wasm-bindgen", "wasm-bindgen-futures", "js-sys"]
