# Copyright (c) 2023 Uber Technologies, Inc.
#
# <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# <p>http://www.apache.org/licenses/LICENSE-2.0
#
# <p>Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing permissions and
# limitations under the License.

# adapted from https://github.com/uber/piranha/blob/1de55fa375609473f524e8117df61bf3a790bd36/tests/tests.py#L138
# changed the Python rule definition into a YAML file
# Ameya from Uber fixed the query

[[rules]]
name= "delete_unused_field"
query = """(
    ((field_declaration
        declarator: (variable_declarator name: (_) @id_name)) @decl)
    (#match? @decl "^private")
    )
"""
replace_node="decl"
replace=""

[[rules.filters]]
enclosing_node= "(class_declaration ) @c_cd"
contains = """(
    (identifier) @name
    (#eq? @name "@id_name")
)"""
at_most= 1
