version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Scan {language} files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "{language}"
