version: "1"
nodes:
  - id: install-deps
    name: Install Dependencies
    type: automatic
    runtime:
      type: direct
    steps:
      - id: npm-install
        name: Install npm packages
        run: npm install

  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    depends_on: [install-deps]
    runtime:
      type: direct
    steps:
      - name: "Remove console.log statements"
        js-ast-grep:
          js_file: "scripts/codemod.ts"
          base_path: "."
          include:
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
          language: "typescript"
