name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.82.0
        id: toolchain
        with:
          components: clippy
      - run: cargo clippy --tests --no-deps -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.82.0
        id: toolchain
        with:
          components: rustfmt
      - run: cargo fmt --check

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.82.0
        id: toolchain
      - name: Run tests
        run: cargo test
      - name: Check schema generation
        run: |
          # Generate schema
          cargo xtask schema
          # Check for uncommitted changes (excluding schemas/workflow.ts)
          if [[ -n "$(git status --porcelain)" ]]; then
            echo '❌ Uncommitted changes detected after running `cargo xtask schema`:'
            git --no-pager diff -- .
            exit 1
          else
            echo "✅ No changes — schema is up to date."
          fi
