name: Continuous Releases

on:
  push:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install modules
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build necessary packages
        run: pnpm build --filter codemod

      - name: Preview
        run: pnpx pkg-pr-new publish './apps/cli' --pnpm --compact
